
name: 'Unit Tests'
description: 'Run unit tests using Node.js'
inputs:
  NODE_VERSION:
    default: "14"
    description: "NodeJS version to be used for the test run"
    required: false
  KEPTN_API_ENDPOINT:
    default: ""
    description: "Keptn API endpoint to be used for test run"
    required: true
  KEPTN_API_TOKEN:
    default: ""
    description: "Keptn API endpoint to be used for test run"
    required: true
runs:
  using: "composite"
  steps: 
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{inputs.NODE_VERSION}}
    - name: Install tsc
      shell: bash
      run: npm install typescript@4.0.2
    - name: Install Dependencies
      shell: bash
      run: npm install && npm run install-all
    - name: Build
      shell: bash
      run: npm run build
    - name: Create keptn endpoint file
      shell: bash
      run: |
        mkdir -p ${HOME}/.keptn
        echo ${{inputs.KEPTN_API_ENDPOINT}} | tee > ${HOME}/.keptn/.keptn
        echo ${{inputs.KEPTN_API_TOKEN}} | tee >> ${HOME}/.keptn/.keptn
    - name: Test
      shell: bash
      run: npm run test-all
