
name: 'Unit Tests'
description: 'Run unit tests using Node.js'
inputs:
  KEPTN_API_ENDPOINT:
    default: ""
    description: "Keptn API endpoint to be used for test run"
    required: true
  KEPTN_API_TOKEN:
    default: ""
    description: "Keptn API endpoint to be used for test run"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install Dependencies
      shell: bash
      run: npm install
    - name: Build
      shell: bash
      run: npm run build
    - name: Create keptn endpoint file
      shell: bash
      run: |
        mkdir -p ${HOME}/.keptn
        echo ${{inputs.KEPTN_API_ENDPOINT}} | tee > ${HOME}/.keptn/.keptn
        echo ${{inputs.KEPTN_API_TOKEN}} | tee >> ${HOME}/.keptn/.keptn
    - name: Test
      shell: bash
      run: npm run test-all
