name: Semantic PR Validation
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  validate:
    uses: keptn/gh-automation/.github/workflows/validate-semantic-pr.yml@main
    with:
      # Configure which scopes are allowed.
      scopes: |
        core
        install
        cloudevents
        deps
        deps-dev
        docs
        release
        azdo
        compatibility
